import { Client, Therapist, GeneratedSchedule, Callout, GAGenerationResult, InsuranceQualification } from '../types';
import { COMPANY_OPERATING_HOURS_START, COMPANY_OPERATING_HOURS_END } from '../constants';
import { validateFullSchedule } from '../utils/validationService';
import { supabase } from '../lib/supabase';

function toLocalYMD(d: Date): string {
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

export async function runCsoAlgorithm(
    clients: Client[],
    therapists: Therapist[],
    insuranceQualifications: InsuranceQualification[],
    selectedDate: Date,
    callouts: Callout[],
    _initialScheduleForOptimization?: GeneratedSchedule
): Promise<GAGenerationResult> {
    const dateString = toLocalYMD(selectedDate);

    console.log("Invoking solve-schedule for date:", dateString);

    try {
        const { data, error } = await supabase.functions.invoke('solve-schedule', {
            body: { date: dateString }
        });

        if (error) {
            console.error("Supabase function invocation error details:", error);
            let errorMessage = error.message || "Unknown error";
            if (errorMessage.includes("Failed to send a request")) {
                errorMessage = "Failed to connect to the scheduling solver. Please ensure the Supabase Edge Function 'solve-schedule' is deployed and reachable. If running locally, make sure 'supabase start' and 'supabase functions serve' are active.";
            }
            return {
                schedule: [],
                finalValidationErrors: [{ ruleId: "SOLVER_ERROR", message: errorMessage }],
                generations: 0,
                bestFitness: 1,
                success: false,
                statusMessage: "Solver Connection Error"
            };
        }

        if (!data || !data.success) {
            console.error("Solver failed to generate a valid schedule:", data);
            return {
                schedule: [],
                finalValidationErrors: [{ ruleId: "SOLVER_FAILED", message: `The solver was unable to find a perfect schedule: ${data?.status || 'Unknown reason'}. This usually happens when constraints (like mandatory lunch breaks or strict insurance requirements) cannot be met for all staff.` }],
                generations: 0,
                bestFitness: 1,
                success: false,
                statusMessage: data?.status || "Infeasible"
            };
        }

        const schedule: GeneratedSchedule = data.schedule;

        const errors = validateFullSchedule(
            schedule,
            clients,
            therapists,
            insuranceQualifications,
            selectedDate,
            COMPANY_OPERATING_HOURS_START,
            COMPANY_OPERATING_HOURS_END,
            callouts
        );

        return {
            schedule,
            finalValidationErrors: errors,
            generations: 1,
            bestFitness: errors.length,
            success: true,
            statusMessage: "Schedule Generated by CP-SAT Solver"
        };

    } catch (err: any) {
        console.error("Unexpected error during schedule generation:", err);
        return {
            schedule: [],
            finalValidationErrors: [{ ruleId: "UNEXPECTED_ERROR", message: `An unexpected error occurred: ${err.message}` }],
            generations: 0,
            bestFitness: 1,
            success: false,
            statusMessage: "Error"
        };
    }
}
