import { Client, Therapist, GeneratedSchedule, Callout, GAGenerationResult, InsuranceQualification } from '../types';
import { COMPANY_OPERATING_HOURS_START, COMPANY_OPERATING_HOURS_END } from '../constants';
import { validateFullSchedule } from '../utils/validationService';
import { supabase } from '../lib/supabase';

function toLocalYMD(d: Date): string {
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

export async function runCsoAlgorithm(
    clients: Client[],
    therapists: Therapist[],
    insuranceQualifications: InsuranceQualification[],
    selectedDate: Date,
    callouts: Callout[],
    _initialScheduleForOptimization?: GeneratedSchedule
): Promise<GAGenerationResult> {
    const dateString = toLocalYMD(selectedDate);

    console.log(`[CSO] Starting optimization for ${dateString} using CP-SAT solver...`);

    try {
        const { data, error } = await supabase.functions.invoke('solve-schedule', {
            body: { date: dateString },
            headers: {
                'Content-Type': 'application/json'
            }
        });

        if (error) {
            console.error("[CSO] Edge Function invocation failed:", error);

            let errorMessage = error.message || "Unknown error";

            // Handle common fetch errors which appear as "Failed to send a request"
            if (errorMessage.includes("Failed to send a request") || errorMessage.includes("TypeError: Load failed")) {
                errorMessage = `Connection Failed: The browser could not reach the scheduling solver.

Please ensure:
1. The Edge Function 'solve-schedule' is deployed to your Supabase project.
2. If running locally, 'supabase start' and 'supabase functions serve' are active.
3. Your internet connection is stable.

Internal details: ${errorMessage}`;
            }

            return {
                schedule: [],
                finalValidationErrors: [{ ruleId: "SOLVER_ERROR", message: errorMessage }],
                generations: 0,
                bestFitness: 1,
                success: false,
                statusMessage: "Solver Connection Error"
            };
        }

        if (!data || !data.success) {
            console.error("[CSO] Solver returned unsuccessful response:", data);
            return {
                schedule: [],
                finalValidationErrors: [{ ruleId: "SOLVER_FAILED", message: `The solver was unable to find a perfect schedule: ${data?.status || 'Unknown reason'}. This usually happens when constraints (like mandatory lunch breaks or strict insurance requirements) cannot be met for all staff with the current availability.` }],
                generations: 0,
                bestFitness: 1,
                success: false,
                statusMessage: data?.status || "Infeasible"
            };
        }

        console.log(`[CSO] Solver success! Received ${data.schedule?.length || 0} entries.`);
        const schedule: GeneratedSchedule = data.schedule;

        // Final validation using existing local rules to ensure parity
        const errors = validateFullSchedule(
            schedule,
            clients,
            therapists,
            insuranceQualifications,
            selectedDate,
            COMPANY_OPERATING_HOURS_START,
            COMPANY_OPERATING_HOURS_END,
            callouts
        );

        return {
            schedule,
            finalValidationErrors: errors,
            generations: 1,
            bestFitness: errors.length,
            success: true,
            statusMessage: "Schedule Generated by CP-SAT Solver"
        };

    } catch (err: any) {
        console.error("[CSO] Unexpected error during schedule generation:", err);
        return {
            schedule: [],
            finalValidationErrors: [{ ruleId: "UNEXPECTED_ERROR", message: `An unexpected error occurred in the scheduler bridge: ${err.message}` }],
            generations: 0,
            bestFitness: 1,
            success: false,
            statusMessage: "Bridge Error"
        };
    }
}
